'use client';

import Image from 'next/image';
import { useEffect, useMemo, useRef, useState } from 'react';

const sections = [['origin','ORIGIN'],['identity','IDENTITY'],['capabilities','CAPABILITIES'],['work','SELECTED WORK'],['archive','ARCHIVE'],['contact','CONTACT']];
const projects = [
 {n:'01',title:'Potter Mobile+',kind:'FULL-STACK COMMERCE',outcome:'A production commerce platform spanning storefront, trade-in, stock, booking, PromptPay payments, live support, AI-assisted pricing, and a complete admin backoffice.',role:'Product design · Full-stack development',year:'2026',tools:'Next.js 16 · Supabase · Claude API',image:'/work/potter-mobile-plus.png',accent:'#75aaff',sigil:'P+',orbit:'COMMERCE / AI / PAYMENTS',href:'https://potter-mobile-plus.vercel.app'},
 {n:'02',title:'Potter Mobile Pawn',kind:'PRODUCTION PWA',outcome:'A production pawn-management system covering contracts, signatures, interest, redemption, cash ledger, role access, and multi-branch audit trails.',role:'Full-stack product development',year:'2026',tools:'Next.js 16 · Supabase · Puppeteer',image:'/work/potter-pawn-live.png',accent:'#8cffc1',sigil:'PP',orbit:'PWA / CONTRACTS / OPERATIONS',href:'https://potter-mobile-pawn.vercel.app/backoffice'},
 {n:'03',title:'Polaris',kind:'SYSTEM + EXTENSION',outcome:'A real-time case reporting dashboard and browser extension connecting support workflows with a legacy enterprise system.',role:'System design · Development',year:'2026',tools:'Next.js · TypeScript · Browser extension',image:'/work/polaris-live.png',accent:'#a8ff60',sigil:'PX',orbit:'DASHBOARD / EXTENSION / SYNC',href:'https://ma-report-app.vercel.app'},
];const archive = [
 ['2026','Potter Mobile Pawn','CODE','Full-stack product development','Next.js / Supabase / Puppeteer / PWA','https://potter-mobile-pawn.vercel.app/backoffice/reports'],
 ['2026','Potter Mobile Plus','CODE','Product design & full-stack development','Next.js / Supabase / Claude API','https://www.pottermobileplus.com'],
 ['2026','Cinema Ticket Booking System','CODE','Full-stack development','Go / Vue 3 / MongoDB / Redis','https://github.com/ZXzep/cinema-booking-system'],
 ['2026','Polaris','CODE','System design & development','Next.js / TypeScript / Chrome extension','https://ma-report-app.vercel.app'],
 ['2025','AI Solutions Marketplace','UX/UI','UX/UI design','Figma / Interactive prototype','https://www.figma.com/proto/866xE0q9aql8rdw6Snnrcw/ai.codelabsdev.co--Copy-?page-id=0%3A1&node-id=512-1331&viewport=-2244%2C287%2C0.13&t=sCAlYmFkWd87P9DS-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=512%3A1331'],
 ['2025','CodeLabs Tech','UX/UI','UX/UI, graphic & brand design','Figma / Illustrator / Canva','https://zxzep.github.io/my-portfolio/project-codelabs.html'],
 ['2025','MindDojo','DESIGN','Graphic design for events & media','Illustrator / Canva','https://zxzep.github.io/my-portfolio/project-minddojo.html'],
 ['—','TA Recruitment','UX/UI','Requirements, wireframes & UX/UI design','Figma','https://zxzep.github.io/my-portfolio/project-ta.html'],
 ['—','Kumi Shop','UX/UI','UX/UI design & front-end development','Figma / Photoshop','https://zxzep.github.io/my-portfolio/project-kumi.html'],
 ['—','TIC-TACTICS','UX/UI','UX/UI design & front-end development','Figma / Front-end','https://zxzep.github.io/my-portfolio/project-ttt.html'],
 ['—','Hoklong Metaverse','3D','3D modeling for metaverse tourism','Maya / Substance 3D Painter','https://zxzep.github.io/my-portfolio/project-horklong.html'],
 ['—','University 3D Project','3D','3D modeling & asset design','Maya / Substance 3D Painter','https://zxzep.github.io/my-portfolio/project-3d-project.html'],
 ['—','Freelance Graphic Design','DESIGN','Artwork for game promotions & events','Illustrator','https://zxzep.github.io/my-portfolio/project-freelance-gp.html'],
];

function Universe(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const c=ref.current;if(!c)return;const x=c.getContext('2d');if(!x)return;let raf=0,t=0,mx=0,my=0,stars:{x:number;y:number;r:number;d:number;a:number}[]=[];const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const size=()=>{const d=Math.min(devicePixelRatio,2);c.width=innerWidth*d;c.height=innerHeight*d;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.setTransform(d,0,0,d,0,0);stars=Array.from({length:Math.min(230,Math.floor(innerWidth/5))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.2+.2,d:Math.random()*3+.4,a:Math.random()*.65+.2}))};const move=(e:PointerEvent)=>{mx=(e.clientX/innerWidth-.5)*10;my=(e.clientY/innerHeight-.5)*8};const draw=()=>{x.clearRect(0,0,innerWidth,innerHeight);for(const s of stars){x.globalAlpha=s.a;x.fillStyle=s.d>2.4?'#bcaeff':'#f5f3ee';x.beginPath();x.arc(s.x+mx*s.d*.18,(s.y+(reduced?0:t*.011*s.d))%innerHeight+my*s.d*.18,s.r,0,Math.PI*2);x.fill()}x.globalAlpha=1;t++;raf=requestAnimationFrame(draw)};size();draw();addEventListener('resize',size);addEventListener('pointermove',move);return()=>{cancelAnimationFrame(raf);removeEventListener('resize',size);removeEventListener('pointermove',move)}},[]);return <canvas ref={ref} className="universe" aria-hidden="true"/>}
function Mission({active,progress}:{active:string;progress:number}){return <nav className="mission" aria-label="Mission progress"><div className="mission-line"><i style={{height:progress+'%'}}/></div>{sections.map(([id,label],i)=><a key={id} href={'#'+id} className={active===id?'active':''} aria-current={active===id?'location':undefined}><span/><b>{String(i).padStart(2,'0')}</b><em>{label}</em></a>)}</nav>}

export default function Home(){const[active,setActive]=useState('origin');const[progress,setProgress]=useState(0);const[filter,setFilter]=useState('ALL');const filtered=useMemo(()=>filter==='ALL'?archive:archive.filter(p=>p[2]===filter),[filter]);useEffect(()=>{const scroll=()=>{setProgress(Math.min(100,scrollY/(document.documentElement.scrollHeight-innerHeight)*100));let current='origin';for(const[id]of sections){const e=document.getElementById(id);if(e&&e.getBoundingClientRect().top<innerHeight*.48)current=id}setActive(current);history.replaceState(null,'','#'+current)};scroll();addEventListener('scroll',scroll,{passive:true});return()=>removeEventListener('scroll',scroll)},[]);return <main>
 <Universe/><div className="noise" aria-hidden="true"/><Mission active={active} progress={progress}/>
 <header className="topbar"><a href="#origin" className="mark">PS<span>✦</span></a><span>CREATIVE UNIVERSE / 2026</span><a href="mailto:zephyrxzep@gmail.com">AVAILABLE FOR WORK <i/></a></header>
 <section id="origin" className="hero section"><div className="coordinates">13.7563° N<br/>100.5018° E</div><div className="hero-copy"><p className="eyebrow">BANGKOK · THAILAND / AVAILABLE WORLDWIDE</p><h1><span>I DESIGN EXPERIENCES</span><span>AND BUILD THEM <em>REAL.</em></span></h1><div className="hero-meta"><p>Punnathat Samoprong is a creative technologist shaping visual identities, digital products, interfaces, 3D experiences, and production-ready software.</p><p className="role">DESIGNER <b>×</b> DEVELOPER</p></div><div className="actions"><a className="button primary" href="#work">EXPLORE THE UNIVERSE <span>↘</span></a><a className="button" href="/Punnathat_Samoprong_Resume.pdf" download>DOWNLOAD RESUME <span>↓</span></a></div></div><div className="orbital" aria-hidden="true"><div className="orbit-label">GRAPHIC · UX/UI · CODE · 3D</div><div className="core"><i/><i/><i/></div></div><div className="scroll-cue"><span>SCROLL TO TRAVEL</span><i/></div></section>
 <section id="identity" className="identity section"><div className="section-index"><span>01</span><p>IDENTITY</p></div><div className="portrait-wrap"><div className="portrait-frame"><Image src="/profile.png" alt="Portrait of Punnathat Samoprong" fill sizes="(max-width:800px) 82vw,38vw"/></div><span>PUNNATHAT / BKK</span></div><div className="identity-copy"><p className="eyebrow">THE PERSON BEHIND THE PIXELS</p><h2>ONE MIND.<br/>MULTIPLE <em>ORBITALS.</em></h2><p className="lead">I move between aesthetics, business systems, and technology—turning complex ideas into experiences people can see, feel, and use.</p><div className="identity-notes"><p><span>BACKGROUND</span>Information Technology graduate from KMITL, specialized in Multimedia & Game Development.</p><p><span>NOW</span>MA Programmer working with Dynamics 365 Business Central, AL, SQL, and production reporting systems.</p><p><span>EXPERIENCE</span>Former Middle UX/UI & Graphic Designer at Codelabs Tech and Graphic Designer at Mind DoJo.</p><p><span>APPROACH</span>From concept and visual direction to UX logic, data, and the final working product.</p></div><div className="keywords"><span>DESIGNER</span><span>DEVELOPER</span><span>PROBLEM SOLVER</span><span>CREATIVE TECHNOLOGIST</span></div></div></section>
 <section id="capabilities" className="capabilities section"><div className="section-index"><span>02</span><p>CAPABILITIES</p></div><div className="section-heading"><p className="eyebrow">THREE DISCIPLINES / ONE SYSTEM</p><h2>CHOOSE A <em>PORTAL.</em></h2></div><div className="portals">{[['VISUAL','#ff5d82','Brand identity|Graphic design|Campaign artwork|Typography|Motion & 3D','PS · AI · AE · BLENDER'],['EXPERIENCE','#5596ff','UX research|Information architecture|Wireframes|Prototypes|Design systems','FIGMA · MIRO · PROTOTYPING'],['CODE','#a8ff60','Next.js & React|Supabase & SQL|Go & distributed systems|ERP / AL Language|Performance & accessibility','TYPESCRIPT · GO · AL · SQL']].map((p,i)=><article className="portal" style={{'--accent':p[1]} as React.CSSProperties} key={p[0]}><span className="portal-num">0{i+1}</span><div className="portal-ring"><i/><i/><span>↗</span></div><h3>{p[0]}</h3><ul>{p[2].split('|').map(x=><li key={x}>{x}</li>)}</ul><p>{p[3]}</p></article>)}</div></section>
 <section id="work" className="work section"><div className="section-index"><span>03</span><p>SELECTED WORK</p></div><div className="section-heading"><p className="eyebrow">FEATURED MISSIONS / 2024—2026</p><h2>WORK WITH <em>GRAVITY.</em></h2></div><div className="projects">{projects.map(p=><article className="project" style={{'--accent':p.accent} as React.CSSProperties} key={p.title}><div className="project-visual"><a className={`project-sigil sigil-${p.n}`} href={p.href} target="_blank" rel="noreferrer" aria-label={`Open ${p.title}`}><span className="sigil-field" aria-hidden="true"><i className="orbit orbit-a"/><i className="orbit orbit-b"/><i className="orbit orbit-c"/><span className="sigil-star">✦</span><b>{p.sigil}</b><em>{p.orbit}</em><span className="satellite satellite-a"/><span className="satellite satellite-b"/><span className="satellite satellite-c"/></span><span className="sigil-status" aria-hidden="true"><i/> LIVE SYSTEM / {p.year}</span></a><span className="project-count">{p.n} / {String(projects.length).padStart(2,'0')}</span></div><div className="project-copy"><p className="eyebrow">{p.kind}</p><h3>{p.title}</h3><p>{p.outcome}</p><dl><div><dt>ROLE</dt><dd>{p.role}</dd></div><div><dt>YEAR</dt><dd>{p.year}</dd></div><div><dt>TOOLS</dt><dd>{p.tools}</dd></div></dl><a className="text-link" href={p.href} target="_blank" rel="noreferrer">VIEW PROJECT <span>↗</span></a></div></article>)}</div></section>
 <section id="archive" className="archive section"><div className="section-index"><span>04</span><p>ARCHIVE</p></div><div className="section-heading archive-head"><div><p className="eyebrow">THE EXTENDED CONSTELLATION</p><h2>PROJECT <em>ARCHIVE.</em></h2></div><div className="filters" role="group" aria-label="Filter projects">{['ALL','DESIGN','UX/UI','CODE','3D'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><div className="archive-list">{filtered.map(p=><a href={p[5]} target="_blank" rel="noreferrer" className="archive-row" key={p[1]}><span>{p[0]}</span><strong>{p[1]}</strong><span>{p[2]}</span><span>{p[3]}</span><span>{p[4]}</span><b>↗</b></a>)}</div></section>
 <section id="contact" className="contact section"><div className="event-horizon" aria-hidden="true"><i/><i/><i/></div><p className="eyebrow">05 / CONTACT · TRANSMISSION OPEN</p><h2>LET’S CREATE<br/><em>SOMETHING UNREAL.</em></h2><p>Have a product to shape, a world to build, or an idea that refuses to stay ordinary?</p><a className="contact-button" href="mailto:zephyrxzep@gmail.com"><span>START A PROJECT</span><b>↗</b></a><div className="contact-details"><a href="mailto:zephyrxzep@gmail.com">zephyrxzep@gmail.com</a><a href="tel:+66987070173">+66 098-707-0173</a></div><footer><span>© 2026 PUNNATHAT SAMOPRONG</span><div><a href="mailto:zephyrxzep@gmail.com">EMAIL</a><a href="https://www.linkedin.com/in/punnathat-samoprong/" target="_blank">LINKEDIN</a><a href="https://github.com/ZXzep" target="_blank">GITHUB</a><a href="/Punnathat_Samoprong_Resume.pdf">RESUME</a></div><span>BANGKOK / WORLDWIDE</span></footer></section>
 </main>}
